### PR TITLE
Cran fix

### PR DESCRIPTION
**Pull request by wincowgerDEV**

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
If we require that the data is downloaded every time the shiny app is opened (since it needs to go to the tempdir) it really punches OSF pretty hard since the files are quite large. If it doesn't work the first time, it seems like the app will start crashing.

**Comment by wincowgerDEV** [comment]
I keep getting this error when trying to download the osf libraries: 
ing: Error in curl::curl_fetch_disk: Send failure: Connection was reset
  50: %>%
  49: get_lib
  48: load_data [G:\My Drive\GrayLab\Projects\Plastics\ActiveProjects\OpenSpecy\Code\Github\inst\shiny/server.R#56]
  47: server [G:\My Drive\GrayLab\Projects\Plastics\ActiveProjects\OpenSpecy\Code\Github\inst\shiny/server.R#132]
Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle) : 
  Send failure: Connection was reset

I wonder if we are hitting osf too hard with the request. Might try slowing it down.

**Comment by wincowgerDEV** [comment]
Consistent failure even with:
 get_lib(path = tempdir(), which = "raman", types = "library")
Fetching Open Specy reference libraries from OSF ... 

Downloading raman_library.rds
  |=====================================================================                              |  70%Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle) : 
  Send failure: Connection was reset

I will try and see if hosting the data on a different platform solves the issue.

**Comment by wincowgerDEV** [comment]
I was able to get the data into the tempdir after osf refusing me a few times. But now the check_lib won't see that they exist. 

check_lib(path = tempdir()) returns NULL

**Comment by wincowgerDEV** [comment]
Maybe it would be better if we just add in a feature in the desktop package version where they can specify where their libraries are. That way people can add to their libraries and organize their files however they would like. Also they can choose to manually download the files and place them somewhere if they have bad internet like me.

**Comment by wincowgerDEV** [comment]
> Maybe it would be better if we just add in a feature in the desktop package version where they can specify where their libraries are. That way people can add to their libraries and organize their files however they would like. Also they can choose to manually download the files and place them somewhere if they have bad internet like me.


Eh! That is going to take a lot of work to build out all of these possible exceptions.

**Comment by wincowgerDEV** [comment]
So this seems to work to read in the files from the temp directory

`readRDS(file.path(paste0(tempdir(), "\\", which[1], "_", types[1], ".rds")))`

**Comment by wincowgerDEV** [comment]
This app or something similar might help us let users tell us where the library is. 

https://github.com/wleepang/shiny-directory-input

**Comment by wincowgerDEV** [comment]
Stopping here for the weekend. My brain is mush. Hopefully, you can think of a better approach. I left a possible avenue if the config file doesn't end up working, there is this location on the match spectrum page where users can specify a folder location.

**Comment by zsteinmetz** [comment]
> Consistent failure even with:
> get_lib(path = tempdir(), which = "raman", types = "library")

Does this still happen? I cannot reproduce it. Maybe OSF was down during the weekend?

**Comment by zsteinmetz** [comment]
> So this seems to work to read in the files from the temp directory
> 
> `readRDS(file.path(paste0(tempdir(), "\\", which[1], "_", types[1], ".rds")))`

Didn't this just work with `spec_lib <- load_lib(path = tempdir())`?

**Comment by zsteinmetz** [comment]
> Maybe it would be better if we just add in a feature in the desktop package version where they can specify where their libraries are. That way people can add to their libraries and organize their files however they would like. Also they can choose to manually download the files and place them somewhere if they have bad internet like me.

Don't know if this is really necessary. If at all, I'd let package users choose their working directory with an argument added to `run_app()` instead of coding it into the UI itself. What do you think?

**Comment by wincowgerDEV** [comment]
I love the idea of letting the user specify it in run_app. I agree it isn't
necessary.

**Comment by wincowgerDEV** [comment]
Yeah it started working magically after a few hours. I think OSF was just
slow for a while.

**Comment by zsteinmetz** [comment]
> I love the idea of letting the user specify it in run_app. I agree it isn't necessary.

Alright. I'll add this to #54.

**Pull request closed without merging**
