### PR TITLE
Improve package documentation

### PR DESCRIPTION
**Pull request by zsteinmetz**
### SOP vignette

- [x] Convert to markdown
- [x] Add images back in
- [x] Adjust to latest changes in Open Specy
- [x] Take new screenshots for Open Specy

~Add to Shiny app as separate tab?~, maybe later @wincowgerDEV?

### Doc files

- [x] `read_hdpe` man page
- [x] `test_lib` man page
- [x] Revise exiting (`@return`, `@references`, ...)

### CODE REVIEW

**Comment by zsteinmetz** [comment]
@wincowgerDEV I started to migrate the Google docs SOP to an R vignette and add some R code to it. Currently, it looks like this:

https://htmlpreview.github.io/?https://github.com/wincowgerDEV/OpenSpecy/blob/improve-docs/vignettes/sop.html

Let me know what you think about it ...

**Comment by wincowgerDEV** [comment]
Awesome! This looks great. I'll have some time to edit it today with the
updated functions and stuff.

**Comment by zsteinmetz** [comment]
> I'll have some time to edit it today with the updated functions and stuff.

Thank you! Feel free to continue working on this branch. I won't get in your way until Monday.

With all that stuff in place (and if validation passes), CRAN is not so far away anymore :sunglasses:

**Comment by wincowgerDEV** [comment]
Awesome! I might try to navigate this into the bookdown format if it isn't
too complicated. Also I'll get the new validation script setup today.

**Comment by zsteinmetz** [comment]
Don't know if this is already worth the effort given that we don't have too much content yet. From what I've seen so far, bookdown conent is usually hosted in a separate repo and not so nicely integrated within the package as a vignette. I'd rather think about creating a separate vignette for specific stuff if the current one become too large .. we could, for example, think about separating the GUI instructions from console stuff ..

**Comment by wincowgerDEV** [comment]
That makes sense. Might as well stick with the vignette for now and build
out some longer stuff later.

**Comment by wincowgerDEV** [comment]
I guess we should also add the functions as a separate part of the vignette. Right now it is mostly centered around the gui and how to use it.

**Comment by wincowgerDEV** [comment]
I would like to add this script to provide an example of the matching but curl keeps throwing an error. `The same table can be returned using the Open Specy library commands in the R Console. 

```{r identification, fig.cap = "Sample `raman_hdpe` spectrum with identified with the Open Specy library (Cowger et al., 2020).", echo=FALSE}
library(ggplot2)
data("raman_hdpe")
get_lib()

# Load library into global environment
spec_lib <- load_lib()

raman_proc <- raman_hdpe %>%
  adjust_intensity() %>% 
  smooth_intensity() %>% 
  subtract_background()

# Match spectrum with library and retrieve meta data
match_spectrum(raman_proc, library = spec_lib, which = "raman")

find_spectrum(sample_name == 5381, library = spec_lib, which = "raman")

````

**Comment by wincowgerDEV** [comment]
I think we have all the latest changes updated now. If we want to add the code above to demonstrate the matching, we may have to find a workaround for it. If not, I think the vignette is good to go. Once we push this change, we should redirect the Open Specy SOP link on the home page to the vignette.

**Comment by zsteinmetz** [comment]
Wow! Thanks for all your input, @wincowgerDEV.


> I would like to add this script to provide an example of the matching but curl keeps throwing an error.

I'll look into this and merge, when I fixed it.

**Comment by zsteinmetz** [comment]
> I would like to add this script to provide an example of the matching but curl keeps throwing an error.

Matching examples are back in. We need to use `eval=FALSE` here since vignettes are build with the package and we don't want to load the full library during package build and CI testing.

**Comment by wincowgerDEV** [comment]
That makes sense! Thanks for fixing that. I'm still learning the markdown
syntax there is so much there. Definitely going to use it more often for
documenting my code.

Cheers,
Win

**Pull request merged**
