### PR TITLE
Testing and polishing app

### PR DESCRIPTION
**Pull request by wincowgerDEV**
Improved UI by turning helper buttons into popup helper messages on hover to decrease clutter. 

Also dealt with this issue:
https://github.com/wincowgerDEV/OpenSpecy/issues/9#issue-823745168

@zsteinmetz I think this is what you were thinking for that feature request?
image

I was able to get the buttons to now completely turn off the process if they are inactivated, and I put all of the tools in the little cog button which will allow us to scale up as we add more tools without making things overly cluttered.

### CODE REVIEW

**Comment by zsteinmetz** [comment]
Nice work! You just need one extra click now to adjust the sliders. Bearable?

**Comment by zsteinmetz** [comment]
> @zsteinmetz I think this is what you were thinking for that feature request?
> image

If we stay with those cog buttons, should be maybe rather place them on the right and add some spacing between the sliders and the text? This would make it more logic from a user's perspective, I guess.

**Comment by wincowgerDEV** [comment]
I can figure out another way to add more features without bogging down the
ui. I think it should be alright for now.

**Comment by wincowgerDEV** [comment]
I agree with the space between the text and slider. It was giving me some
trouble. As for where the cog should be, if you try out the cogs you'll see
that they end up pooping out in a location right below the slider which to
me made intuitive sense but I'm open to other ideas. Also it's good to have
the cog information not cover the plot so you don't want it too far to the
right.

**Comment by zsteinmetz** [comment]
Hmm, doesn't seem ideal to me. You'd like to decide for switching a tool on or off first and do the fine tuning afterwards with the sliders. Given that the default language is English reading from left to right, this is not consistent. I'll contemplate a little more on that.

**Comment by wincowgerDEV** [comment]
There might be a way we can have the tool button open to the left or
something too which would satisfy all the things.

**Pull request merged**
