### PR TITLE
More unit testing

### PR DESCRIPTION
**Pull request by zsteinmetz**
For `read_*` functions and spectra processing.

**TODOs**
`manage_lib` and `match_spectrum()` still need testing routines.

@wincowgerDEV Could you maybe produce a set of 100 random Raman spectra for testing purposes and add them to OSF as `test_library.rds` and `test_metadata.rds`?

### CODE REVIEW

**Comment by zsteinmetz** [comment]
@wincowgerDEV Do you have an idea why `read_spa()` keeps failing on Windows? I don't have a Windows machine at hand to check and debug.

I guess, the problem is somewhere here:

https://github.com/wincowgerDEV/OpenSpecy/blob/1feb5a0fbbb8c7e8039e5ad7c53b1067e5e1220c/R/read_spectra.R#L50-L57

Is `mgn` empty?

**Comment by zsteinmetz** [comment]
I commented the test out for now that checks pass but we shouldn't merge until this is fixed.

**Comment by wincowgerDEV** [comment]
> For `read_*` functions and spectra processing.
> 
> **TODOs**
> `manage_lib` and `match_spectrum()` still need testing routines.
> 
> @wincowgerDEV Could you maybe produce a set of 100 random Raman spectra for testing purposes and add them to OSF as `test_library.rds` and `test_metadata.rds`?

I just added "augmented_ftir.rds" and "augmented_raman.rds" to the osf repo. 

image

Basically what these are is an augmented version of the libraries. I just added random noise and baseline to the spectra in there so you can merge the sample_name to the metadata files and get all their metadata. 

New variable explanations:
intensity_og is the original intensity in the library spectra just normalized. 
intensity_aug1 is the original intensity with noise added. 
intensity_aug2 is the original intensity with noise and baseline sift added.

**Comment by wincowgerDEV** [comment]
> I commented the test out for now that checks pass but we shouldn't merge until this is fixed.

I am testing it out on my device. 

The original read_spa function from the open specy website works on my device, but this new formatted function doesn't work. Did the original function work on your device? Was there a reason you made the changes you did?

**Comment by zsteinmetz** [comment]
> I just added "augmented_ftir.rds" and "augmented_raman.rds" to the osf repo.

Ah no, .. seems like we talked past each other :see_no_evil: sorry!

My idea behind the testdata was not to have random/augmented spectra but to have a smaller subset of the current reference library (max. 100 spectra randomly picked from the large one) to run unit tests on them. This is because downloading the complete library just to test if e.g. `get_lib()` or `match_spectrum()` works as expected will just take too long and uses up traffic.

Hope producing the augmented data set didn't take too much of your time.

**Comment by zsteinmetz** [comment]
> The original read_spa function from the open specy website works on my device, but this new formatted function doesn't work. Did the original function work on your device? Was there a reason you made the changes you did?

> I guess readLines used to be the read_table function which we changed from to decrease dependencies. We could just revert back to using the read_table function for now until we figure out why this issue is happening only on Windows.

The original function worked on my machine but needed readr (see #6), yes. That's why I changed some bits of the code. You're right, the first `readLines()` was the culprit. II was able to fix it so no need to take readr back in :wink:

**Comment by wincowgerDEV** [comment]
No worries! We need the augmented data to test the full work flow for
accuracy eventually anyways.

I'll make the 100 spectra subsets from the libraries today.

Cheers
Win

**Pull request merged**
