### PR TITLE
Log fix

### PR DESCRIPTION
**Pull request by wincowgerDEV**
Improve logging of events in shiny.

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
@zsteinmetz I figured out how to get the logging working with a combination of mongolite and loggit. Loggit will work if the app is on the desktop and mongo will work if on shinyapps. They store the data as basically carbon copies for cross compatibility. With this update, we can remove google analytics which I think will make it so that we don't have any third party cookies on the website. Need to double check that cookies aren't getting created somewhere else though. The logging is also now dependant on the user selection of "share data" so that they don't have to get logged if they don't want to. 

One thing we need to still do is make sure that the loggit file is going to the tempdir or a dir that the user wants it to go to. Perhaps we can make that compatible with the location that the user specifies where their library files or maybe we should make that a unique location?

**Comment by zsteinmetz** [comment]
Awesome work!

**Comment by zsteinmetz** [comment]
I think we're set.

**Comment by wincowgerDEV** [comment]
@zsteinmetz great work! I agree. I think we are ready.

**Pull request merged**
